
export interface Currency {
    code: string;
    name: string;
    country: string;
}

export const CURRENCY_DATA: Currency[] = [
    { code: 'USD', name: 'US Dollar', country: 'United States' },
    { code: 'LKR', name: 'Sri Lankan Rupee', country: 'Sri Lanka' },
    { code: 'EUR', name: 'Euro', country: 'European Union' },
    { code: 'GBP', name: 'British Pound', country: 'United Kingdom' },
    { code: 'JPY', name: 'Japanese Yen', country: 'Japan' },
    { code: 'AUD', name: 'Australian Dollar', country: 'Australia' },
    { code: 'CAD', name: 'Canadian Dollar', country: 'Canada' },
    { code: 'CHF', name: 'Swiss Franc', country: 'Switzerland' },
    { code: 'CNY', name: 'Chinese Yuan', country: 'China' },
    { code: 'INR', name: 'Indian Rupee', country: 'India' },
    { code: 'BRL', name: 'Brazilian Real', country: 'Brazil' },
    { code: 'RUB', name: 'Russian Ruble', country: 'Russia' },
    { code: 'ZAR', name: 'South African Rand', country: 'South Africa' },
    { code: 'MXN', name: 'Mexican Peso', country: 'Mexico' },
    { code: 'KRW', name: 'South Korean Won', country: 'South Korea' },
    { code: 'IDR', name: 'Indonesian Rupiah', country: 'Indonesia' },
    { code: 'TRY', name: 'Turkish Lira', country: 'Turkey' },
    { code: 'SAR', name: 'Saudi Riyal', country: 'Saudi Arabia' },
    { code: 'NGN', name: 'Nigerian Naira', country: 'Nigeria' },
    { code: 'SEK', name: 'Swedish Krona', country: 'Sweden' },
    { code: 'PLN', name: 'Polish Zloty', country: 'Poland' },
    { code: 'NOK', name: 'Norwegian Krone', country: 'Norway' },
    { code: 'DKK', name: 'Danish Krone', country: 'Denmark' },
    { code: 'SGD', name: 'Singapore Dollar', country: 'Singapore' },
    { code: 'MYR', name: 'Malaysian Ringgit', country: 'Malaysia' },
    { code: 'THB', name: 'Thai Baht', country: 'Thailand' },
    {
        code: 'AED',
        name: 'United Arab Emirates Dirham',
        country: 'United Arab Emirates',
    },
    { code: 'ARS', name: 'Argentine Peso', country: 'Argentina' },
    { code: 'CLP', name: 'Chilean Peso', country: 'Chile' },
    { code: 'COP', name: 'Colombian Peso', country: 'Colombia' },
    { code: 'PEN', name: 'Peruvian Sol', country: 'Peru' },
    { code: 'EGP', name: 'Egyptian Pound', country: 'Egypt' },
    { code: 'VND', name: 'Vietnamese Dong', country: 'Vietnam' },
    { code: 'PKR', name: 'Pakistani Rupee', country: 'Pakistan' },
    { code: 'BDT', name: 'Bangladeshi Taka', country: 'Bangladesh' },
    { code: 'HUF', name: 'Hungarian Forint', country: 'Hungary' },
    { code: 'CZK', name: 'Czech Koruna', country: 'Czech Republic' },
    { code: 'ILS', name: 'Israeli New Shekel', country: 'Israel' },
    { code: 'NZD', name: 'New Zealand Dollar', country: 'New Zealand' },
    { code: 'QAR', name: 'Qatari Riyal', country: 'Qatar' },
    { code: 'KWD', name: 'Kuwaiti Dinar', country: 'Kuwait' },
    { code: 'OMR', name: 'Omani Rial', country: 'Oman' },
    { code: 'BHD', name: 'Bahraini Dinar', country: 'Bahrain' },
    { code: 'MAD', name: 'Moroccan Dirham', country: 'Morocco' },
    { code: 'TWD', name: 'New Taiwan Dollar', country: 'Taiwan' },
    { code: 'PHP', name: 'Philippine Peso', country: 'Philippines' },
    { code: 'RON', name: 'Romanian Leu', country: 'Romania' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', country: 'Ukraine' },
    { code: 'GHS', name: 'Ghanaian Cedi', country: 'Ghana' },
    { code: 'KES', name: 'Kenyan Shilling', country: 'Kenya' },
    { code: 'TZS', name: 'Tanzanian Shilling', country: 'Tanzania' },
    { code: 'UGX', name: 'Ugandan Shilling', country: 'Uganda' },
    { code: 'LBP', name: 'Lebanese Pound', country: 'Lebanon' },
    { code: 'JOD', name: 'Jordanian Dinar', country: 'Jordan' },
    { code: 'IQD', name: 'Iraqi Dinar', country: 'Iraq' },
    { code: 'DZD', name: 'Algerian Dinar', country: 'Algeria' },
    { code: 'TND', name: 'Tunisian Dinar', country: 'Tunisia' },
    { code: 'DOP', name: 'Dominican Peso', country: 'Dominican Republic' },
    { code: 'HTG', name: 'Haitian Gourde', country: 'Haiti' },
    { code: 'JMD', name: 'Jamaican Dollar', country: 'Jamaica' },
    {
        code: 'TTD',
        name: 'Trinidad and Tobago Dollar',
        country: 'Trinidad and Tobago',
    },
    { code: 'BBD', name: 'Barbadian Dollar', country: 'Barbados' },
    { code: 'BMD', name: 'Bermudian Dollar', country: 'Bermuda' },
    { code: 'KYD', name: 'Cayman Islands Dollar', country: 'Cayman Islands' },
    { code: 'BSD', name: 'Bahamian Dollar', country: 'Bahamas' },
    { code: 'GYD', name: 'Guyanese Dollar', country: 'Guyana' },
    { code: 'SRD', name: 'Surinamese Dollar', country: 'Suriname' },
    {
        code: 'ANG',
        name: 'Netherlands Antillean Guilder',
        country: 'Netherlands Antilles',
    },
    { code: 'AWG', name: 'Aruban Florin', country: 'Aruba' },
    {
        code: 'XCD',
        name: 'East Caribbean Dollar',
        country: 'Eastern Caribbean',
    },
    { code: 'BZD', name: 'Belize Dollar', country: 'Belize' },
    { code: 'NAD', name: 'Namibian Dollar', country: 'Namibia' },
    { code: 'BWP', name: 'Botswana Pula', country: 'Botswana' },
    { code: 'ZMW', name: 'Zambian Kwacha', country: 'Zambia' },
    { code: 'MWK', name: 'Malawian Kwacha', country: 'Malawi' },
    { code: 'LSL', name: 'Lesotho Loti', country: 'Lesotho' },
    { code: 'SZL', name: 'Swazi Lilangeni', country: 'Eswatini' },
    { code: 'MZN', name: 'Mozambican Metical', country: 'Mozambique' },
    { code: 'BIF', name: 'Burundian Franc', country: 'Burundi' },
    { code: 'RWF', name: 'Rwandan Franc', country: 'Rwanda' },
    {
        code: 'CDF',
        name: 'Congolese Franc',
        country: 'Democratic Republic of the Congo',
    },
    {
        code: 'XOF',
        name: 'West African CFA Franc',
        country: 'West African Economic and Monetary Union',
    },
    {
        code: 'XAF',
        name: 'Central African CFA Franc',
        country: 'Central African Economic and Monetary Community',
    },
    { code: 'DJF', name: 'Djiboutian Franc', country: 'Djibouti' },
    { code: 'ERN', name: 'Eritrean Nakfa', country: 'Eritrea' },
    { code: 'ETB', name: 'Ethiopian Birr', country: 'Ethiopia' },
    { code: 'MGA', name: 'Malagasy Ariary', country: 'Madagascar' },
    { code: 'SCR', name: 'Seychellois Rupee', country: 'Seychelles' },
    { code: 'MUR', name: 'Mauritian Rupee', country: 'Mauritius' },
    { code: 'KES', name: 'Kenyan Shilling', country: 'Kenya' },
    { code: 'SOS', name: 'Somali Shilling', country: 'Somalia' },
    { code: 'SHP', name: 'Saint Helena Pound', country: 'Saint Helena' },
    { code: 'ZWL', name: 'Zimbabwean Dollar', country: 'Zimbabwe' },
    {
        code: 'BAM',
        name: 'Bosnia and Herzegovina Convertible Mark',
        country: 'Bosnia and Herzegovina',
    },
    { code: 'MKD', name: 'Macedonian Denar', country: 'North Macedonia' },
    { code: 'ALL', name: 'Albanian Lek', country: 'Albania' },
    { code: 'BYN', name: 'Belarusian Ruble', country: 'Belarus' },
    { code: 'MDL', name: 'Moldovan Leu', country: 'Moldova' },
    { code: 'GEL', name: 'Georgian Lari', country: 'Georgia' },
    { code: 'AZN', name: 'Azerbaijani Manat', country: 'Azerbaijan' },
    { code: 'AMD', name: 'Armenian Dram', country: 'Armenia' },
    { code: 'KZT', name: 'Kazakhstani Tenge', country: 'Kazakhstan' },
    { code: 'UZS', name: 'Uzbekistani Som', country: 'Uzbekistan' },
    { code: 'TJS', name: 'Tajikistani Somoni', country: 'Tajikistan' },
    { code: 'KGS', name: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
    { code: 'AFN', name: 'Afghan Afghani', country: 'Afghanistan' },
    { code: 'IRR', name: 'Iranian Rial', country: 'Iran' },
    { code: 'YER', name: 'Yemeni Rial', country: 'Yemen' },
    { code: 'SYP', name: 'Syrian Pound', country: 'Syria' },
    { code: 'LBP', name: 'Lebanese Pound', country: 'Lebanon' },
    { code: 'JOD', name: 'Jordanian Dinar', country: 'Jordan' },
    { code: 'ILS', name: 'Israeli New Shekel', country: 'Israel' },
    { code: 'IQD', name: 'Iraqi Dinar', country: 'Iraq' },
    { code: 'KWD', name: 'Kuwaiti Dinar', country: 'Kuwait' },
    { code: 'BHD', name: 'Bahraini Dinar', country: 'Bahrain' },
    { code: 'QAR', name: 'Qatari Riyal', country: 'Qatar' },
    { code: 'OMR', name: 'Omani Rial', country: 'Oman' },
    {
        code: 'AED',
        name: 'United Arab Emirates Dirham',
        country: 'United Arab Emirates',
    },
    { code: 'SAR', name: 'Saudi Riyal', country: 'Saudi Arabia' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', country: 'Maldives' },
    { code: 'BTN', name: 'Bhutanese Ngultrum', country: 'Bhutan' },
    { code: 'NPR', name: 'Nepalese Rupee', country: 'Nepal' },
    { code: 'PKR', name: 'Pakistani Rupee', country: 'Pakistan' },
    { code: 'BDT', name: 'Bangladeshi Taka', country: 'Bangladesh' },
    { code: 'LKR', name: 'Sri Lankan Rupee', country: 'Sri Lanka' },
    { code: 'INR', name: 'Indian Rupee', country: 'India' },
    { code: 'KHR', name: 'Cambodian Riel', country: 'Cambodia' },
    { code: 'LAK', name: 'Lao Kip', country: 'Laos' },
    { code: 'MMK', name: 'Burmese Kyat', country: 'Myanmar' },
    { code: 'THB', name: 'Thai Baht', country: 'Thailand' },
    { code: 'SGD', name: 'Singapore Dollar', country: 'Singapore' },
    { code: 'MYR', name: 'Malaysian Ringgit', country: 'Malaysia' },
    { code: 'IDR', name: 'Indonesian Rupiah', country: 'Indonesia' },
    { code: 'PHP', name: 'Philippine Peso', country: 'Philippines' },
    { code: 'VND', name: 'Vietnamese Dong', country: 'Vietnam' },
    { code: 'CNY', name: 'Chinese Yuan', country: 'China' },
    { code: 'HKD', name: 'Hong Kong Dollar', country: 'Hong Kong' },
    { code: 'TWD', name: 'New Taiwan Dollar', country: 'Taiwan' },
    { code: 'MOP', name: 'Macanese Pataca', country: 'Macau' },
    { code: 'KRW', name: 'South Korean Won', country: 'South Korea' },
    { code: 'KPW', name: 'North Korean Won', country: 'North Korea' },
    { code: 'JPY', name: 'Japanese Yen', country: 'Japan' },
    { code: 'AUD', name: 'Australian Dollar', country: 'Australia' },
    { code: 'NZD', name: 'New Zealand Dollar', country: 'New Zealand' },
    { code: 'FJD', name: 'Fijian Dollar', country: 'Fiji' },
    {
        code: 'PGK',
        name: 'Papua New Guinean Kina',
        country: 'Papua New Guinea',
    },
    { code: 'SBD', name: 'Solomon Islands Dollar', country: 'Solomon Islands' },
    { code: 'TOP', name: 'Tongan Paʻanga', country: 'Tonga' },
    { code: 'WST', name: 'Samoan Tala', country: 'Samoa' },
    { code: 'KID', name: 'Kiribati Dollar', country: 'Kiribati' },
    { code: 'VUV', name: 'Vanuatu Vatu', country: 'Vanuatu' },
    { code: 'XPF', name: 'CFP Franc', country: 'French Polynesia' },
    { code: 'BND', name: 'Brunei Dollar', country: 'Brunei' },
];

