name: CI/CD

on:
  push:
    branches:
      - main
    # If someone updates the paths which has been mentioned in "paths-ignore", then workflow will not run for that.
    paths-ignore:
      #- 'helm/**' # Exclude the workflow to run on changes to the helm chart
      #- 'k8s/**'
      - 'README.md'
      #- '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm i --legacy-peer-deps

    - name: Build Angular app
      run: npm run build -- --configuration=production
    
    # - name: Test Angular app
    #   run: npm run test -- --watch=false --code-coverage

  # code-quality:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
    
  #   # Run static code analysis for Angular using ESLint
  #   - name: Run ESLint
  #     run: npm run lint  
  
  push:
    runs-on: ubuntu-latest

    needs: build
    # This indicate that to trigger this stage, "build" stage has to be completed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tender-management-portal:${{github.run_id}}
        # Whenever a developer make a commit, the tag  of docker image will create with new run id

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push
        # This indicate that to trigger this stage, "push" stage has to be completed


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/tender-management-portal-chart/values.yaml
      # this sed commnad first will  go to helm directory then will go to the values.yml, after it will update anything that is in the tag.
      # It will substitute the tag with github run id
    
      # Once values.yml is updated by using sed command , we have to push the commit again to our  same repository    
    - name: Commit and push changes
      run: |
        git config --global user.email "sachinayeshmantha@gmail.com"
        git config --global user.name "Sachin20010517"
        git add helm/tender-management-portal-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push      